### ISSUE TITLE
`caption-side: block-XXX` does not exist in the CSS specification

### ISSUE THREAD

**Issue by SaekiTominaga** [yuschick/stylelint-plugin-logical-css#30]
**Describe the bug**

The logical value of `caption-side` is only `inline-start` and `inline-end`. 👉[CSS Spec](https://drafts.csswg.org/css-logical-1/#caption-side)

> The existing top and bottom values are idiosyncratically redefined as assigning to the block-start and block-end sides of the table, respectively.

**Expected behavior**

The following CSS will not cause an error.

```css
.caption-block-start {
	caption-side: top;
}

.caption-block-end {
	caption-side: bottom;
}
```

**Additional context**

- Proposal to add `block-XXX` to the CSS specification 👉w3c/csswg-drafts/issues/9623
- PR to correct MDN documentation 👉mdn/content/pull/30291
